volumes:
  unisimple_postgres:
services:
  app:
    build:
      context: .
      dockerfile: "backend.Dockerfile"
    ports:
      - "11002:11002"
    restart: always
  postgres:
    image: "postgres:17-alpine"
    restart: "always"
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_DB=${DB_NAME}"
    volumes:
      - "unisimple_postgres:/var/lib/postgresql/data"
      - "./src/db/init_scripts:/docker-entrypoint-initdb.d"
    ports:
      - "${DB_PORT}:5432"
